# Generated by Django 5.1.2 on 2024-10-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bs_id", models.IntegerField(verbose_name="序号")),
                ("bs_toid", models.IntegerField(verbose_name="资产类汇总序号")),
                ("bs_var", models.CharField(max_length=8, verbose_name="变量名")),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "material_id",
                    models.CharField(max_length=10, unique=True, verbose_name="物料号"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="名称",
                    ),
                ),
                ("unit", models.CharField(max_length=5, verbose_name="单位")),
                (
                    "allocation_method",
                    models.CharField(max_length=10, verbose_name="调配方式"),
                ),
                ("loss_rate", models.FloatField(verbose_name="损耗率")),
                ("lead_time", models.IntegerField(verbose_name="作业提前期")),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "material_name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="物料名称",
                    ),
                ),
                ("workshop_inventory", models.IntegerField(verbose_name="工序库存")),
                ("material_inventory", models.IntegerField(verbose_name="资材库存")),
                (
                    "material_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="myapp.material",
                        to_field="material_id",
                        verbose_name="物料号",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MPSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mps_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="MPS编号"
                    ),
                ),
                ("required_quantity", models.IntegerField(verbose_name="需求数量")),
                ("due_date", models.DateField(verbose_name="完工日期")),
                (
                    "material_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mps_records",
                        to="myapp.material",
                        verbose_name="产品名称",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillOfMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50, verbose_name="描述")),
                ("quantity", models.IntegerField(verbose_name="装配数量")),
                ("unit", models.CharField(max_length=2, verbose_name="单位")),
                ("level", models.IntegerField(verbose_name="层次")),
                (
                    "material_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boms",
                        to="myapp.material",
                        to_field="material_id",
                        verbose_name="物料号",
                    ),
                ),
            ],
            options={
                "unique_together": {("description", "level")},
            },
        ),
        migrations.CreateModel(
            name="AllocationComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_code",
                    models.CharField(max_length=10, verbose_name="调配基准编号"),
                ),
                (
                    "region_code",
                    models.CharField(max_length=10, verbose_name="调配区域代码"),
                ),
                (
                    "parent_material_name",
                    models.CharField(max_length=20, verbose_name="父物料名称"),
                ),
                (
                    "child_material_name",
                    models.CharField(max_length=20, verbose_name="子物料名称"),
                ),
                ("quantity", models.IntegerField(verbose_name="构成数量")),
                (
                    "allocation_lead_time",
                    models.IntegerField(verbose_name="配料提前期"),
                ),
                (
                    "supplier_lead_time",
                    models.IntegerField(verbose_name="供应商提前期"),
                ),
                (
                    "child_material_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_compositions",
                        to="myapp.material",
                        to_field="material_id",
                        verbose_name="子物料号",
                    ),
                ),
                (
                    "parent_material_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_compositions",
                        to="myapp.material",
                        to_field="material_id",
                        verbose_name="父物料号",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent_material_name", "child_material_name")},
            },
        ),
    ]
