# Generated by Django 5.1.2 on 2024-10-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocationcomposition",
            name="child_material_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_compositions",
                to="myapp.material",
                verbose_name="子物料号",
            ),
        ),
        migrations.AlterField(
            model_name="allocationcomposition",
            name="parent_material_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_compositions",
                to="myapp.material",
                verbose_name="父物料号",
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="material_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boms",
                to="myapp.material",
                verbose_name="物料号",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="material_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="myapp.material",
                verbose_name="物料号",
            ),
        ),
        migrations.AlterField(
            model_name="mpsrecord",
            name="mps_id",
            field=models.CharField(max_length=10, unique=True, verbose_name="MPS编号"),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="material_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_plans",
                to="myapp.material",
                verbose_name="物料号",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseplan",
            name="material_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_plans",
                to="myapp.material",
                verbose_name="物料号",
            ),
        ),
    ]
