# Generated by Django 5.1.2 on 2024-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_code",
                    models.CharField(max_length=10, verbose_name="调配基准编号"),
                ),
                (
                    "region_code",
                    models.CharField(max_length=10, verbose_name="调配区域代码"),
                ),
                (
                    "parent_material_code",
                    models.CharField(max_length=10, verbose_name="父物料号"),
                ),
                (
                    "parent_material_name",
                    models.CharField(max_length=20, verbose_name="父物料名称"),
                ),
                (
                    "child_material_code",
                    models.CharField(max_length=10, verbose_name="子物料号"),
                ),
                (
                    "child_material_name",
                    models.CharField(max_length=20, verbose_name="子物料名称"),
                ),
                ("quantity", models.IntegerField(verbose_name="构成数量")),
                (
                    "allocation_lead_time",
                    models.IntegerField(verbose_name="配料提前期"),
                ),
                (
                    "supplier_lead_time",
                    models.IntegerField(verbose_name="供应商提前期"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillOfMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=10, verbose_name="零件号")),
                ("description", models.CharField(max_length=50, verbose_name="描述")),
                ("quantity", models.IntegerField(verbose_name="装配数量")),
                ("unit", models.CharField(max_length=2, verbose_name="单位")),
                ("level", models.IntegerField(verbose_name="层次")),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=10, verbose_name="物料号"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=20, verbose_name="物料名称"),
                ),
                ("workshop_inventory", models.IntegerField(verbose_name="工序库存")),
                ("material_inventory", models.IntegerField(verbose_name="资材库存")),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=10, verbose_name="物料号"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("unit", models.CharField(max_length=5, verbose_name="单位")),
                (
                    "allocation_method",
                    models.CharField(max_length=10, verbose_name="调配方式"),
                ),
                ("loss_rate", models.FloatField(verbose_name="损耗率")),
                ("lead_time", models.IntegerField(verbose_name="作业提前期")),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
