# Generated by Django 5.1.2 on 2024-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_mps"),
    ]

    operations = [
        migrations.CreateModel(
            name="MPSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=10, verbose_name="物料编号"),
                ),
                ("required_quantity", models.IntegerField(verbose_name="需求数量")),
                ("due_date", models.DateField(verbose_name="需求日期")),
            ],
        ),
    ]
