# Generated by Django 5.1.2 on 2024-10-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_mpsrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=10, verbose_name="物料号"),
                ),
                ("quantity", models.IntegerField(verbose_name="生产数量")),
                ("date", models.DateField(verbose_name="计划日期")),
            ],
        ),
        migrations.CreateModel(
            name="PurchasePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=10, verbose_name="物料号"),
                ),
                ("quantity", models.IntegerField(verbose_name="采购数量")),
                ("date", models.DateField(verbose_name="计划日期")),
            ],
        ),
    ]
